### ISSUE TITLE
Keeping the original words and only modernizing the spelling

### ISSUE THREAD

**Issue by truthsword** [deeproots/books#16]
Let me provide examples of how I am (and am not) doing this.

For the most part, I have left archaic words as is (my spell checker's custom word list is vastly larger now)). I believe that to “modernize” these terms risks interpretational nuances beyond the author’s intent.

Examples of terms I've retained include; doest, believeth, delightest, stablish, and the like. 

What I have changed involves primarily British spellings. For example, I’ve changed...

fulness to fullness
specialising to specializing
Saviour to Savior; favour to favor…

Food for thought,

**Comment by lukewil** [comment]
I am going to write up some documentation about spellings soon, but **we're exactly on the same page**. Two things that bother me though:
1.  You're finding British spellings like `Saviour` often? They should have been fixed before I pushed the original texts. :-1: That really bothers me, gonna have to investigate.
2.  `Stablish` is the one word that I have changed, because the difference between the old and modern usage is literally nothing but the addition of the e, but without it the old one just look like a typo! Even if it was `stablisheth`, to me `establisheth` seems so much clearer.

**Comment by truthsword** [comment]
Re; Saviour/Savior; favour/favor... I can't say it's appeared "often," but it has occurred, and I've added it to a checklist I keep to sweep through the document after I've read through/formatted things.

Another archaic word I've retained that I was unfamiliar with is "fain".

One peculiarity I've come across is that the word "self-sacrifice" was entirely absent from 3 Murray books. Very odd. So much so, that I now OCR the "original.pdf" for my own use, so I can search the original text for different occurrences.

I'm OK with adding the "e" to "stablish" and its derivatives. I'dd add that to my punchlist.

**Comment by lukewil** [comment]
Interesting. I just checked the `gulpfile.js` that's doing all the search/replaces, and both `favour` and `Saviour` should have been caught. Makes me wonder what else it's missing. Going to have to do some testing now. :worried: 

What are you using to OCR the PDF?

**Comment by truthsword** [comment]
I use ABBYY Transformer for OCR. It's not a serious production tool (I'd probably use ABBY Fine Reader), but economical for my use. It will come in handy reverting Holy Spirit to Holy Ghost, for in Murray's "_Absolute Surrender_", both terms are present (and not just from KJV citations either). 

Holy Ghost - 76 instances
Holy Spirit - 98 instances

**Comment by truthsword** [comment]
Just thinking aloud here... but would your find/replace scheme recognize "Saviour" in these forms...
Saviour:
Saviour;
Saviour—
—Saviour

... possibly as well there may have been missing spaces in the text file..."Saviourcame", 

Most representations I saw were shown as "Savior".

**Comment by lukewil** [comment]
I'm using regular expressions for the search, with "word boundaries" (`\b`) on either side of the word. I'll have to research and see, but I believe punctuation should be considered a word boundary.
